#
# Used by github actions to build and push docker image to ECR
#

version: '3'

vars:
  AWS_REGION: "eu-west-2"

tasks:
  build:
    desc: Build this docker image
    dir: src
    cmds:
      - docker build -t sfrunner:latest-amd64 --build-arg ARCH=amd64/ .
      - docker build -t sfrunner:latest-arm64v8 --build-arg ARCH=arm64v8/ .

  run:
    desc: Runs a shell inside the sfrunner image
    cmds:
      - docker run --rm --volume $HOME:/localhost sfrunner:latest --login

  install:
    desc: Gives script to install 'sfrunner' as local command
    cmds:
      - docker run --rm --volume $HOME:/localhost sfrunner:latest init | bash

  ecr-login:
    internal: false
    desc: Docker login to ECR so one can send/receive docker images.  Must have role assumed, via Leapp
    cmds:
      - aws ecr get-login-password --region {{.AWS_REGION}} | docker login --username AWS --password-stdin {{.ECR_HOST}}

  ecr-push:
    desc: Pushes the sfrunner image to ECR
    vars:
      ECR_REPO: '{{.ECR_HOST}}/{{.REPO_NAME}}'
    cmds:
      - task: ecr-login
      - docker tag sfrunner:latest-amd64 {{.ECR_REPO}}:latest-amd64
      - docker push {{.ECR_REPO}}:latest-amd64
      - docker tag sfrunner:latest-arm64 {{.ECR_REPO}}:latest-arm64
      - docker push {{.ECR_REPO}}:latest-arm64
      - docker docker manifest create {{.ECR_REPO}}:latest --amend {{.ECR_REPO}}:latest-amd64 --amend {{.ECR_REPO}}:latest-arm64v8
      - docker manifest push {{.ECR_REPO}}:latest

  ecr-install:
    desc: Installs sfrunner from remote ECR repo
    vars:
      ECR_HOST: '{{.ECR_HOST}}'
      REPO_NAME: '{{.REPO_NAME}}'
    requires:
      vars: [ECR_HOST, REPO_NAME]
    deps:
      - task: ecr-login
        vars:
          ECR_HOST: '{{.ECR_HOST}}'
    cmds:
      - docker run --rm --volume $HOME:/localhost {{.ECR_HOST}}/{{.REPO_NAME}}:latest init | bash
