name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build docker image
        run: task build

