name: Build and ECR push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION : eu-west-2

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build docker image (arm64)
        run: task build PLATFORM_SUFFIX=arm64 PLATFORM=linux/arm64/v8 AWS_ACC=${{ secrets.AWS_ACC }}
      - name: Build docker image (amd64)
        run: task build PLATFORM_SUFFIX=amd64 PLATFORM=linux/amd64 AWS_ACC=${{ secrets.AWS_ACC }}
      - name: Log into AWS
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWSOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Push docker image (arm64)
        run: task ecr-push ECR_HOST=${{ secrets.ECR_HOST }} REPO_NAME=${{ secrets.REPO_NAME }} PLATFORM_SUFFIX=arm64
      - name: Push docker image (amd64)
        run: task ecr-push ECR_HOST=${{ secrets.ECR_HOST }} REPO_NAME=${{ secrets.REPO_NAME }} PLATFORM_SUFFIX=amd64
      - name: Push manifest
        run: task push-manifest ECR_HOST=${{ secrets.ECR_HOST }} REPO_NAME=${{ secrets.REPO_NAME }}

