name: uec-sf-Github-connection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION : eu-west-2

permissions:
  id-token: write
  contents: read

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutCode
        uses: actions/checkout@v3
      - name: Log into AWS
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::730319765130:role/uec-sf-github-access
          role-session-name: GitHub_to_AWSOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: AWS STS whoAmI
        run: |
          aws sts get-caller-identity